export const hero_types = {
  ALIEN: {'type': 'Alien', 'backgroundColor': 'lightblue'},
  ANGEL: {'type': 'Angel', 'backgroundColor': 'lightblue'},
  CENTAUR: {'type': 'Centaur', 'backgroundColor': 'lightblue'},
  DEMON: {'type': 'Demon', 'backgroundColor': 'lightblue'},
  DRAGON: {'type': 'Dragon', 'backgroundColor': 'lightblue'},
  ELF: {'type': 'Elf', 'backgroundColor': 'lightblue'},
  FAIRY: {'type': 'Fairy', 'backgroundColor': 'lightblue'},
  GIANT: {'type': 'Giant', 'backgroundColor': 'lightblue'},
  GNOME: {'type': 'Gnome', 'backgroundColor': 'lightblue'},
  GOBLIN: {'type': 'Goblin', 'backgroundColor': 'lightblue'},
  IMP: {'type': 'Imp', 'backgroundColor': 'lightblue'},
  OGRE: {'type': 'Ogre', 'backgroundColor': 'lightblue'},
  ORK: {'type': 'Ork', 'backgroundColor': 'lightblue'},
  PIXIE: {'type': 'Pixie', 'backgroundColor': 'lightblue'},
  SEA_MONSTER: {'type': 'Sea Monster', 'backgroundColor': 'lightblue'},
  TROLL: {'type': 'Troll', 'backgroundColor': 'lightblue'},
  UNICORN: {'type': 'Unicorn', 'backgroundColor': 'lightblue'},
  VAMPIRE: {'type': 'Vampire', 'backgroundColor': 'lightblue'},
  WEREWOLF: {'type': 'Werewolf', 'backgroundColor': 'lightblue'},
  WITCH: {'type': 'Witch', 'backgroundColor': 'lightblue'},
  WIZARD: {'type': 'Wizard', 'backgroundColor': 'lightblue'},
  YETI: {'type': 'Yeti', 'backgroundColor': 'lightblue'},
  ZOMBIE: {'type': 'Zombie', 'backgroundColor': 'lightblue'},
};

export const hero_names_and_types = [
  {'name': 'Caprirge'},
  {'name': 'Rhaelge'},
  {'name': 'Geovous'},
  {'name': 'Coxmane'},
  {'name': 'Neycox Skyrge'},
  {'name': 'Kramge Georflame'},
  {'name': 'Coxsmoke'},
  {'name': 'Coth'},
  {'name': "Helrge Do'george"},
  {'name': 'Georgegobblette'},
  {'name': 'Frankencox'},
  {'name': 'Cacklerge Colline'},
  {'name': 'Geobotty'},
  {'name': 'Cotoria Neongeorge'},
  {'name': 'Drusgeorge Coswoon'},
  {'name': 'Georgeriona'},
  {'name': 'Georganta'},
  {'name': 'Shizcox'},
  {'name': 'Coflutter'},
  {'name': 'Yoge'},
  {'name': 'Georgeyanka'},
  {'name': 'Rottorge'},
  {'name': 'Coda'},
  {'name': 'Fanggeorge'},
  {'name': 'Geobiella'},
  {'name': 'Spaceco'},
  {'name': 'Titange'},
  {'name': 'The Georumble'},
  {'name': 'Geoknee Forest'},
  {'name': 'Co Coxondancer'},
  {'name': 'Cheekrge'},
  {'name': 'Georgeganta'},
  {'name': 'Codelia'},
  {'name': 'Georaconda'},
  {'name': 'Brainscox'},
  {'name': 'Geopuff'},
  {'name': 'Olage'},
  {'name': 'Piranhageor'},
  {'name': 'Battlege'},
  {'name': 'Georinabla'},
  {'name': 'Cocked'},
  {'name': 'Coxgoodness'},
  {'name': 'Georgeshine'},
  {'name': 'Willrge Cullgeorge'},
  {'name': 'Cophine Geopin'},
  {'name': 'Silvergeor'},
  {'name': 'Cauldron Harkrage'},
  {'name': 'Geoheart'},
  {'name': 'Arige'},
  {'name': 'Crococox'},
  {'name': 'Coxalama'},
  {'name': 'Cotrouble'},
  {'name': 'Coxbell'},
  {'name': 'Coxin Geong Coxm'},
  {'name': 'Stinkge'},
  {'name': 'Abalcox'},
  {'name': 'Georiela'},
  {'name': 'Georgeninki'},
  {'name': 'Georgecheek'},
  {'name': 'Pointygeo Grangcox'},
  {'name': 'Cotha'},
  {'name': 'Grindygeorge'},
  {'name': 'Georstomp'},
  {'name': 'Georbow'},
  {'name': 'Dracoge'},
  {'name': 'Georgedrina'},
  {'name': 'Coganta'},
  {'name': 'Wickedgeorge'},
  {'name': 'Coxtenna The Coxtt'},
  {'name': 'Reanimge'},
  {'name': 'Angecox'},
  {'name': 'Forage Flame'},
  {'name': 'Georgepus'},
  {'name': 'Greengeo Georgeger'},
  {'name': 'Rusalgeorge'},
  {'name': 'Rainrge'},
  {'name': 'Scrcox'},
  {'name': 'Geoshu'},
  {'name': 'Georfang Geocoffin'},
  {'name': 'Geoslight'},
  {'name': 'Coxblex'},
  {'name': 'Ifera'},
  {'name': 'Hydracox'},
  {'name': 'Zimrge'},
  {'name': 'Georallopa'},
  {'name': 'Georgeshark'},
  {'name': 'Mashgeorge'},
  {'name': 'Cogatia'},
  {'name': 'Georgedazzle'},
  {'name': 'Gargantcox'},
  {'name': 'Georhowla Coback'},
  {'name': 'Coxow Pakecox'},
  {'name': 'Coxphira'},
  {'name': 'Malcox Geonic'},
  {'name': 'Coxoo'},
  {'name': 'Coxstenchia'},
  {'name': 'Codigo'},
  {'name': 'Lobstrosgeorge'},
  {'name': 'Georgetwinkle'},
  {'name': 'Jargeorge'},
];
