export const hero_types = {
  ALIEN: {'type': 'Alien', 'backgroundColor': 'lightblue'},
  ANGEL: {'type': 'Angel', 'backgroundColor': 'lightblue'},
  CENTAUR: {'type': 'Centaur', 'backgroundColor': 'lightblue'},
  DEMON: {'type': 'Demon', 'backgroundColor': 'lightblue'},
  DRAGON: {'type': 'Dragon', 'backgroundColor': 'lightblue'},
  ELF: {'type': 'Elf', 'backgroundColor': 'lightblue'},
  FAIRY: {'type': 'Fairy', 'backgroundColor': 'lightblue'},
  GIANT: {'type': 'Giant', 'backgroundColor': 'lightblue'},
  GNOME: {'type': 'Gnome', 'backgroundColor': 'lightblue'},
  GOBLIN: {'type': 'Goblin', 'backgroundColor': 'lightblue'},
  IMP: {'type': 'Imp', 'backgroundColor': 'lightblue'},
  OGRE: {'type': 'Ogre', 'backgroundColor': 'lightblue'},
  ORK: {'type': 'Ork', 'backgroundColor': 'lightblue'},
  PIXIE: {'type': 'Pixie', 'backgroundColor': 'lightblue'},
  SEA_MONSTER: {'type': 'Sea Monster', 'backgroundColor': 'lightblue'},
  TROLL: {'type': 'Troll', 'backgroundColor': 'lightblue'},
  UNICORN: {'type': 'Unicorn', 'backgroundColor': 'lightblue'},
  VAMPIRE: {'type': 'Vampire', 'backgroundColor': 'lightblue'},
  WEREWOLF: {'type': 'Werewolf', 'backgroundColor': 'lightblue'},
  WITCH: {'type': 'Witch', 'backgroundColor': 'lightblue'},
  WIZARD: {'type': 'Wizard', 'backgroundColor': 'lightblue'},
  YETI: {'type': 'Yeti', 'backgroundColor': 'lightblue'},
  ZOMBIE: {'type': 'Zombie', 'backgroundColor': 'lightblue'},
};

export const hero_names_and_types = [
  {'name': 'Caprirge', ...hero_types.SEA_MONSTER},
  {'name': 'Rhaelge', ...hero_types.DRAGON},
  {'name': 'Geovous', ...hero_types.IMP},
  {'name': 'Coxmane', ...hero_types.UNICORN},
  {'name': 'Neycox Skyrge', ...hero_types.ALIEN},
  {'name': 'Kramge Georflame', ...hero_types.DEMON},
  {'name': 'Coxsmoke', ...hero_types.DRAGON},
  {'name': 'Coth', ...hero_types.FAIRY},
  {'name': "Helrge Do'george", ...hero_types.ELF},
  {'name': 'George Gobblette', ...hero_types.GOBLIN},
  {'name': 'Frankencox', ...hero_types.ZOMBIE},
  {'name': 'Cacklerge Colline', ...hero_types.WITCH},
  {'name': 'Geobotty', ...hero_types.ALIEN},
  {'name': 'Cotoria Neongeorge', ...hero_types.ALIEN},
  {'name': 'Drusgeorge Coswoon', ...hero_types.VAMPIRE},
  {'name': 'Georgeriona', ...hero_types.DRAGON},
  {'name': 'Georganta', ...hero_types.GIANT},
  {'name': 'Shizcox', ...hero_types.FAIRY},
  {'name': 'Coflutter', ...hero_types.FAIRY},
  {'name': 'Yoge', ...hero_types.ALIEN},
  {'name': 'Georgeyanka', ...hero_types.DEMON},
  {'name': 'Rottorge', ...hero_types.ZOMBIE},
  {'name': 'Coda', ...hero_types.ALIEN},
  {'name': 'Fanggeorge', ...hero_types.ORK},
  {'name': 'Geobiella', ...hero_types.DEMON},
  {'name': 'Spaceco', ...hero_types.ALIEN},
  {'name': 'Titange', ...hero_types.FAIRY},
  {'name': 'The Georumble', ...hero_types.YETI},
  {'name': 'Geoknee Forest', ...hero_types.PIXIE},
  {'name': 'Coe Moondancer', ...hero_types.ALIEN},
  {'name': 'Cheekrge', ...hero_types.GNOME},
  {'name': 'Georgeganta', ...hero_types.GIANT},
  {'name': 'Codelia', ...hero_types.DEMON},
  {'name': 'Georaconda', ...hero_types.SEA_MONSTER},
  {'name': 'Brainscox', ...hero_types.ZOMBIE},
  {'name': 'Geopuff', ...hero_types.DRAGON},
  {'name': 'Olage', ...hero_types.TROLL},
  {'name': 'Piranhageor', ...hero_types.SEA_MONSTER},
  {'name': 'Battlege', ...hero_types.SEA_MONSTER},
  {'name': 'Georinabla', ...hero_types.YETI},
  {'name': 'Cocked', ...hero_types.GOBLIN},
  {'name': 'Coxgoodness', ...hero_types.ANGEL},
  {'name': 'Georgeshine', ...hero_types.ANGEL},
  {'name': 'Willrge Cullgeorge', ...hero_types.VAMPIRE},
  {'name': 'Cophine Geopin', ...hero_types.WEREWOLF},
  {'name': 'Silvergeor', ...hero_types.UNICORN},
  {'name': 'Cauldron Harkrge', ...hero_types.WIZARD},
  {'name': 'Geoheart', ...hero_types.DEMON},
  {'name': 'Arige', ...hero_types.FAIRY},
  {'name': 'Crococox', ...hero_types.SEA_MONSTER},
  {'name': 'Coxalama', ...hero_types.DEMON},
  {'name': 'Cotrouble', ...hero_types.IMP},
  {'name': 'Coxbell', ...hero_types.FAIRY},
  {'name': 'Coxin Geong Coxm', ...hero_types.DRAGON},
  {'name': 'Stinkge', ...hero_types.OGRE},
  {'name': 'Abalcox', ...hero_types.DEMON},
  {'name': 'Georiela', ...hero_types.ANGEL},
  {'name': 'Georgeninki', ...hero_types.DEMON},
  {'name': 'Georgecheek', ...hero_types.GNOME},
  {'name': 'Pointygeo Grangcox', ...hero_types.WIZARD},
  {'name': 'Cotha', ...hero_types.GIANT},
  {'name': 'Grindygeorge', ...hero_types.SEA_MONSTER},
  {'name': 'Georstomp', ...hero_types.OGRE},
  {'name': 'Georbow', ...hero_types.UNICORN},
  {'name': 'Dracoge', ...hero_types.DRAGON},
  {'name': 'Georgedrina', ...hero_types.ELF},
  {'name': 'Coganta', ...hero_types.GIANT},
  {'name': 'Wickedgeorge', ...hero_types.GOBLIN},
  {'name': 'Coxtenna The Coxtt', ...hero_types.ALIEN},
  {'name': 'Reanimge', ...hero_types.ZOMBIE},
  {'name': 'Angecox', ...hero_types.ANGEL},
  {'name': 'Fornge Flame', ...hero_types.DEMON},
  {'name': 'Georgepus', ...hero_types.DEMON},
  {'name': 'Greengeo Georgeger', ...hero_types.WIZARD},
  {'name': 'Rusalgeorge', ...hero_types.DEMON},
  {'name': 'Rainrge', ...hero_types.UNICORN},
  {'name': 'Scrcox', ...hero_types.TROLL},
  {'name': 'Geoshu', ...hero_types.DRAGON},
  {'name': 'Georfang Geocoffin', ...hero_types.VAMPIRE},
  {'name': 'Geoslight', ...hero_types.GNOME},
  {'name': 'Coxblex', ...hero_types.DEMON},
  {'name': 'Ifera', ...hero_types.DEMON},
  {'name': 'Hydracox', ...hero_types.SEA_MONSTER},
  {'name': 'Zimrge', ...hero_types.DEMON},
  {'name': 'Georallopa', ...hero_types.CENTAUR},
  {'name': 'Georgeshark', ...hero_types.SEA_MONSTER},
  {'name': 'Mashgeorge', ...hero_types.YETI},
  {'name': 'Cogatia', ...hero_types.DEMON},
  {'name': 'Georgedazzle', ...hero_types.UNICORN},
  {'name': 'Gargantcox', ...hero_types.GIANT},
  {'name': 'Georhowla Coback', ...hero_types.WEREWOLF},
  {'name': 'Coxow Pakecox', ...hero_types.VAMPIRE},
  {'name': 'Coxphira', ...hero_types.DRAGON},
  {'name': 'Malcox Geonic', ...hero_types.DEMON},
  {'name': 'Coxoo', ...hero_types.UNICORN},
  {'name': 'Coxstenchia', ...hero_types.TROLL},
  {'name': 'Codigo', ...hero_types.YETI},
  {'name': 'Lobstros George', ...hero_types.SEA_MONSTER},
  {'name': 'Georgetwinkle', ...hero_types.FAIRY},
  {'name': 'Jargeorge', ...hero_types.FAIRY},
];
